### ISSUE TITLE
Problems redirecting to the www subdomain

### ISSUE THREAD

**Issue by jaffacakerhubarb** [chromium/hstspreload.appspot.com#51] opened 2016-07-04 19:49 UTC
Hi all. I can't figure out how to fix my .htaccess file to not throw up an error — namely, 'Error: HTTP redirects to www first.'

`http://acmewidgets.com` (HTTP) should immediately redirect to `https://acmewidgets.com` (HTTPS) before adding the www subdomain. Right now, the first redirect is to `https://www.acmewidgets.com/`.

My .htaccess file is as follows. Can anyone tell me what I'm doing wrong? I've experimented but it just ends up breaking my redirect. 😢

```
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS

RewriteCond %{HTTP_HOST} ^acmewidgets.com [NC]
RewriteRule ^(.*)$ https://www.acmewidgets.com/$1 [L,R=301]
```

**Comment by lgarron** [comment] 2016-07-04 20:12
Redirect to HTTPS first:

    RewriteCond %{HTTPS} off
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

If you want the main site on the `www` subdomain, add it once you're on HTTPS:

    RewriteCond %{HTTPS} on
    RewriteCond %{HTTP_HOST} acmewidgets.com [NC]
    RewriteRule ^(.*)$ https://www.acmewidgets.com/$1 [L,R=301]

**Comment by jaffacakerhubarb** [comment] 2016-07-05 00:14
Thanks for the pointers. I have tried setting my .htaccess like that, but it doesn't seem to work. If I set it as follows:

```
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS

RewriteCond %{HTTPS} off
RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [R,L]

RewriteCond %{HTTPS} on
RewriteCond %{HTTP_HOST} acmewidgets.com [NC]
RewriteRule ^(.*)$ https://www.acmewidgets.com/$1 [L,R=301]
```

Then the page itself refuses to load due to 'too many redirects', and the HSTS preload page gives me this error twice: 'There are more than 3 redirects starting from `http://acmewidgets.com`.'

Am I coding this in wrong?

**Comment by lgarron** [comment] 2016-07-05 00:25
> Then the page itself refuses to load due to 'too many redirects', and the HSTS preload page gives me this error twice: 'There are more than 3 redirects starting from http://acmewidgets.com.'

Whoops, I think the second-to-last line needs to be:

> `RewriteCond %{HTTP_HOST} ^acmewidgets.com$ [NC]`

**Comment by lgarron** [comment] 2016-07-17 06:25
Closing this, since it's not a bug to do with the submission site.

**Closed by lgarron** 2016-07-17 06:25 UTC
